apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nimbusx-data-plane.fullname" . }}
  labels:
    {{- include "nimbusx-data-plane.labels" . | nindent 4 }}
data:
  NIMBUSX_ENV: private-data-plane
  NIMBUSX_CONTROL_PLANE_HEARTBEAT_URL: {{ required "config.heartbeatUrl is required" .Values.config.heartbeatUrl | quote }}
  NIMBUSX_DATA_PLANE_ID: {{ required "config.dataPlaneId is required" .Values.config.dataPlaneId | quote }}